//! Finite production-VM conformance cases for formal/CounterMachine.lean.
//! Expected transitions come from direct natural-number counter rules; the
//! source generator independently spells out the vector/stack translation.

use ourochronos::parser::parse;
use ourochronos::{
    admit_program, AdmissionConfig, BoundsPolicy, BytecodeProgram, BytecodeVm, BytecodeVmConfig,
    BytecodeVmError, BytecodeVmStatus, PagedMemory, PreparedBytecode,
};

#[derive(Clone, Copy, Debug)]
enum Instruction {
    Inc(usize, u64),
    DecJz(usize, u64, u64),
    Halt,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct CounterState {
    counters: [usize; 2],
    pc: u64,
    halted: bool,
}

fn expected_step(instruction: Instruction, mut state: CounterState) -> CounterState {
    match instruction {
        Instruction::Inc(counter, next) => {
            state.counters[counter] += 1;
            state.pc = next;
        }
        Instruction::DecJz(counter, zero, nonzero) => {
            if state.counters[counter] == 0 {
                state.pc = zero;
            } else {
                state.counters[counter] -= 1;
                state.pc = nonzero;
            }
        }
        Instruction::Halt => state.halted = true,
    }
    state
}

fn initialization(state: CounterState) -> String {
    let mut source = String::from("VEC_NEW 0 VEC_PUSH 0 PROPHECY\nVEC_NEW 0 VEC_PUSH 1 PROPHECY\n");
    source.push_str(&format!("{} 2 PROPHECY\n", state.pc));
    for (counter, count) in state.counters.iter().enumerate() {
        for _ in 0..*count {
            source.push_str(&format!("{counter} PRESENT 1 VEC_PUSH POP\n"));
        }
    }
    source
}

fn emitted_instruction(instruction: Instruction) -> String {
    match instruction {
        Instruction::Inc(counter, next) => {
            format!("{counter} PRESENT 1 VEC_PUSH POP {next} 2 PROPHECY")
        }
        Instruction::DecJz(counter, zero, nonzero) => format!(
            "{counter} PRESENT VEC_POP IF {{ POP {nonzero} 2 PROPHECY }} \
             ELSE {{ 0 VEC_PUSH POP {zero} 2 PROPHECY }}"
        ),
        Instruction::Halt => "HALT".to_string(),
    }
}

fn emitted_dispatch(program: &[(u64, Instruction)]) -> String {
    match program.split_first() {
        None => "HALT".to_string(),
        Some(((label, instruction), rest)) => format!(
            "2 PRESENT {label} EQ IF {{ {} }} ELSE {{ {} }}",
            emitted_instruction(*instruction),
            emitted_dispatch(rest)
        ),
    }
}

fn compile(source: &str) -> BytecodeProgram {
    let program = parse(source).expect("generated source must parse");
    let admitted = admit_program(&program, AdmissionConfig { memory_cells: 4 })
        .expect("generated source must satisfy production admission");
    let bytes = admitted.program().to_bytes().unwrap();
    BytecodeProgram::from_bytes(&bytes).expect("generated bytecode must survive artifact decoding")
}

fn assert_execution(source: &str, expected: CounterState) {
    let bytecode = compile(source);
    let vm = BytecodeVm::with_config(BytecodeVmConfig {
        max_instructions: 100_000,
        memory_bounds: BoundsPolicy::Error,
        ..BytecodeVmConfig::default()
    });
    let initial = PagedMemory::with_size(4).unwrap();
    let prepared = PreparedBytecode::new(bytecode.clone()).unwrap();
    for execution in [
        vm.run(&bytecode, &initial),
        vm.run_prepared(&prepared, &initial),
    ] {
        let result = execution.expect("finite translated run must execute successfully");
        assert_eq!(
            result.status,
            if expected.halted {
                BytecodeVmStatus::Halted
            } else {
                BytecodeVmStatus::Finished
            },
            "{source}"
        );
        assert!(
            result.stack.is_empty(),
            "translation must balance its stack"
        );
        assert!(result.output.is_empty());
        assert!(result.effects.is_empty());
        assert_eq!(result.present.get(2).unwrap().val, expected.pc);
        for counter in 0..2 {
            let handle = result.present.get(counter as u64).unwrap().val;
            assert_eq!(handle, counter as u64, "fixed fresh vector handles");
            let actual: Vec<_> = result
                .data_structures
                .vectors
                .get(handle)
                .unwrap()
                .iter()
                .map(|value| value.val)
                .collect();
            let expected_tokens: Vec<_> = std::iter::once(0)
                .chain(std::iter::repeat_n(1, expected.counters[counter]))
                .collect();
            assert_eq!(actual, expected_tokens, "counter {counter}: {source}");
        }
    }
}

#[test]
fn each_emitted_instruction_matches_natural_counter_rules() {
    for first in 0..=3 {
        for second in 0..=3 {
            let initial = CounterState {
                counters: [first, second],
                pc: 5,
                halted: false,
            };
            for instruction in [
                Instruction::Inc(0, u64::MAX),
                Instruction::Inc(1, 7),
                Instruction::DecJz(0, 8, 9),
                Instruction::DecJz(1, 10, 11),
                Instruction::Halt,
            ] {
                let source = initialization(initial) + &emitted_instruction(instruction);
                assert_execution(&source, expected_step(instruction, initial));
            }
        }
    }
}

#[test]
fn translated_dispatch_and_loop_transfer_tokens_and_preserve_zero_sentinels() {
    // Transfer all first-counter tokens, then test that zero counter twice.
    // Repeating DECJZ at zero detects failure to restore the popped sentinel.
    let program = [
        (0, Instruction::DecJz(0, 2, 1)),
        (1, Instruction::Inc(1, 0)),
        (2, Instruction::DecJz(0, 3, 99)),
        (3, Instruction::DecJz(0, 4, 99)),
        (4, Instruction::Halt),
        (99, Instruction::Inc(0, 99)),
    ];
    for count in 0..=12 {
        let initial = CounterState {
            counters: [count, 0],
            pc: 0,
            halted: false,
        };
        let mut expected = initial;
        for _ in 0..100 {
            if expected.halted {
                break;
            }
            let instruction = program.iter().find(|(pc, _)| *pc == expected.pc).unwrap().1;
            expected = expected_step(instruction, expected);
        }
        assert!(expected.halted, "reference case must terminate");
        assert_eq!(expected.counters, [0, count]);
        let source = initialization(initial)
            + &format!("WHILE {{ 1 }} {{ {} }}", emitted_dispatch(&program));
        assert_execution(&source, expected);
    }
}

#[test]
fn conventional_execution_of_nonhalting_translation_exhausts_gas() {
    let initial = CounterState {
        counters: [0, 0],
        pc: 0,
        halted: false,
    };
    let source = initialization(initial)
        + &format!(
            "WHILE {{ 1 }} {{ {} }}",
            emitted_dispatch(&[(0, Instruction::Inc(0, 0))])
        );
    let bytecode = compile(&source);
    let vm = BytecodeVm::with_config(BytecodeVmConfig {
        max_instructions: 200,
        ..BytecodeVmConfig::default()
    });
    assert!(matches!(
        vm.run(&bytecode, &PagedMemory::with_size(4).unwrap()),
        Err(BytecodeVmError::GasExhausted { .. })
    ));
}
